# Generated by Django 4.2.10 on 2024-03-11 14:10

from django.db import migrations, models
import sdu_dorm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='about')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner_img', models.ImageField(default='profile_pics/default.jpg', upload_to='main_page')),
                ('main_title', models.TextField(default='Mail title')),
                ('main_description', models.TextField(default='some text for test')),
                ('mission_title', models.TextField(default='Mission title')),
                ('mission_description', models.TextField(default='Mission description')),
                ('responsibilities_title', models.TextField(default='Responsibilities title')),
                ('responsibilities_description', models.TextField(default='Responsibilities description')),
                ('deadlines_title', models.TextField(default='Deadlines title')),
                ('deadlines_description', models.TextField(default='Deadlines')),
                ('docs_required_title', models.TextField(default='Docs title')),
                ('decs_required_description', models.TextField(default='Decs description')),
                ('dorm_image1', models.ImageField(blank=True, upload_to='main_page/dorm_images')),
                ('dorm_image2', models.ImageField(blank=True, upload_to='main_page/dorm_images')),
                ('dorm_image3', models.ImageField(blank=True, upload_to='main_page/dorm_images')),
                ('dorm_image4', models.ImageField(blank=True, upload_to='main_page/dorm_images')),
                ('dorm_image5', models.ImageField(blank=True, upload_to='main_page/dorm_images')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='student_id')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='is_staff')),
                ('age', models.IntegerField(blank=True, default=18)),
                ('gender', models.BooleanField(default=True)),
                ('grade', models.IntegerField(blank=True, default=1)),
                ('major', models.CharField(blank=True, default='is', max_length=25)),
                ('status', models.BooleanField(default=True)),
                ('additional_info', models.TextField(default='Test')),
                ('reservation', models.CharField(blank=True, max_length=4)),
                ('profile_pic', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('isStudent', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', sdu_dorm.models.AuthUserManager()),
            ],
        ),
    ]
