# Generated by Django 4.2.10 on 2024-03-17 21:06

from django.db import migrations, models
import django.db.models.deletion
import sdu_dorm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='The description')),
                ('name_of_head_of_dormitory', models.CharField(default='Name', max_length=30)),
                ('contacts_head_of_dormitory', models.TextField(blank=True, default='email@mail.com +77079999999')),
                ('contacts_reception', models.TextField(blank=True, default='+77017777777')),
                ('contacts_medical_care', models.TextField(blank=True, default='+77050010101')),
                ('contacts_security_service', models.TextField(blank=True, default='+77778881122')),
                ('main_image1', models.ImageField(upload_to='about/main')),
                ('main_image2', models.ImageField(upload_to='about/main')),
                ('main_image3', models.ImageField(upload_to='about/main')),
                ('main_image4', models.ImageField(upload_to='about/main')),
                ('main_image5', models.ImageField(upload_to='about/main')),
                ('social_life_description', models.TextField(blank=True, default='Social life description')),
                ('social_life_image1', models.ImageField(upload_to='about/social_life')),
                ('social_life_image2', models.ImageField(upload_to='about/social_life')),
                ('social_life_image3', models.ImageField(upload_to='about/social_life')),
                ('social_life_image4', models.ImageField(upload_to='about/social_life')),
                ('social_life_image5', models.ImageField(upload_to='about/social_life')),
                ('social_life_image6', models.ImageField(upload_to='about/social_life')),
                ('social_life_image7', models.ImageField(upload_to='about/social_life')),
                ('social_life_image8', models.ImageField(upload_to='about/social_life')),
                ('safety_members', models.TextField(default='70 members')),
                ('safety_description', models.TextField(blank=True, default='safety description')),
                ('working_hours', models.TextField(blank=True, default='Working hours')),
                ('working_hours_description', models.TextField(blank=True, default='are from 6:00 to 22:00')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_banner_img', models.ImageField(default='profile_pics/default.jpg', upload_to='main_page')),
                ('main_title', models.TextField(default='Mail title')),
                ('main_description', models.TextField(default='some text for test')),
                ('mission_title', models.TextField(default='Mission title')),
                ('mission_description', models.TextField(default='Mission description')),
                ('responsibilities_title', models.TextField(default='Responsibilities title')),
                ('responsibilities_description', models.TextField(default='Responsibilities description')),
                ('deadlines_title', models.TextField(default='Deadlines title')),
                ('deadlines_description', models.TextField(default='Deadlines')),
                ('docs_required_title', models.TextField(default='Docs title')),
                ('decs_required_description', models.TextField(default='Decs description')),
                ('dorm_image1', models.ImageField(blank=True, upload_to='main_page/dorm_images')),
                ('dorm_image2', models.ImageField(blank=True, upload_to='main_page/dorm_images')),
                ('dorm_image3', models.ImageField(blank=True, upload_to='main_page/dorm_images')),
                ('dorm_image4', models.ImageField(blank=True, upload_to='main_page/dorm_images')),
                ('dorm_image5', models.ImageField(blank=True, upload_to='main_page/dorm_images')),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(default='News title')),
                ('news_description', models.TextField(default='News description')),
                ('main_image', models.ImageField(upload_to=sdu_dorm.models.news_image_upload)),
                ('what_to_expect', models.TextField(blank=True)),
                ('registration', models.TextField(blank=True, default='Registration')),
                ('additional_info', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_of_the_event', models.DateField(blank=True)),
                ('time_of_the_event', models.TimeField(blank=True)),
                ('place_of_the_event', models.TextField(blank=True)),
                ('category_of_the_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdu_dorm.newscategories')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='student_id')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='is_staff')),
                ('age', models.IntegerField(blank=True, default=18)),
                ('gender', models.BooleanField(default=True)),
                ('grade', models.FloatField(blank=True, default=1)),
                ('major', models.CharField(blank=True, default='is', max_length=25)),
                ('status', models.BooleanField(default=True)),
                ('reservation', models.CharField(blank=True, max_length=4)),
                ('profile_pic', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('isStudent', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', sdu_dorm.models.AuthUserManager()),
            ],
        ),
    ]
