# Generated by Django 4.2.10 on 2024-02-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_info',
            field=models.TextField(default='Test'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, default=18),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isStudent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, default='is', max_length=25),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='media/profile_pics/default.jpg', upload_to='media/profile_pics'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reservation',
            field=models.CharField(default='123', max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
