# Generated by Django 4.2.10 on 2024-03-13 15:25

from django.db import migrations, models
import django.db.models.deletion
import sdu_dorm.models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(default='News title')),
                ('news_description', models.TextField(default='News description')),
                ('main_image', models.ImageField(upload_to=sdu_dorm.models.news_image_upload)),
                ('what_to_expect', models.JSONField(blank=True)),
                ('registration', models.TextField(blank=True, default='Registration')),
                ('additional_info', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_of_the_event', models.DateField(blank=True)),
                ('time_of_the_event', models.TimeField(blank=True)),
                ('place_of_the_event', models.TextField(blank=True)),
                ('category_of_the_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdu_dorm.newscategories')),
            ],
        ),
    ]
