# Generated by Django 4.2.10 on 2024-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpost',
            name='main_image1',
            field=models.ImageField(blank=True, upload_to='about/main'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='main_image2',
            field=models.ImageField(blank=True, upload_to='about/main'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='main_image3',
            field=models.ImageField(blank=True, upload_to='about/main'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='main_image4',
            field=models.ImageField(blank=True, upload_to='about/main'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='main_image5',
            field=models.ImageField(blank=True, upload_to='about/main'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='social_life_image1',
            field=models.ImageField(blank=True, upload_to='about/social_life'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='social_life_image2',
            field=models.ImageField(blank=True, upload_to='about/social_life'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='social_life_image3',
            field=models.ImageField(blank=True, upload_to='about/social_life'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='social_life_image4',
            field=models.ImageField(blank=True, upload_to='about/social_life'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='social_life_image5',
            field=models.ImageField(blank=True, upload_to='about/social_life'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='social_life_image6',
            field=models.ImageField(blank=True, upload_to='about/social_life'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='social_life_image7',
            field=models.ImageField(blank=True, upload_to='about/social_life'),
        ),
        migrations.AlterField(
            model_name='aboutpost',
            name='social_life_image8',
            field=models.ImageField(blank=True, upload_to='about/social_life'),
        ),
    ]
