# Generated by Django 4.2.10 on 2024-03-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0002_alter_aboutpost_main_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpost',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
