# Generated by Django 4.2.10 on 2024-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0002_customuser_additional_info_customuser_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpiece',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
