# Generated by Django 4.2.10 on 2024-02-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0003_alter_aboutpiece_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='student_id',
        ),
    ]
