# Generated by Django 4.2.10 on 2024-03-21 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0003_aboutpost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
