# Generated by Django 4.2.10 on 2024-03-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0004_alter_customuser_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='additional_info',
        ),
    ]
