# Generated by Django 4.2.10 on 2024-04-22 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0004_alter_paymentmodel_invoiceid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.FileField(upload_to='documents/applications')),
                ('photo', models.FileField(upload_to='documents/photos')),
                ('identity_card', models.FileField(upload_to='documents/identity_cards')),
                ('form_075', models.FileField(upload_to='documents/form_075')),
                ('payment_check', models.FileField(upload_to='documents/checks')),
                ('power_of_attorney', models.FileField(upload_to='documents/powers_of_attorney')),
                ('address_certificate', models.FileField(upload_to='documents/address_certificates')),
                ('university_admission_form', models.FileField(upload_to='documents/admission_forms')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
