# Generated by Django 4.2.10 on 2024-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0005_uploaddocumentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship',
            field=models.IntegerField(default=0),
        ),
    ]
