# Generated by Django 4.2.10 on 2024-03-28 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0006_alter_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormModel',
            fields=[
                ('block', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('taraf', models.IntegerField()),
                ('room', models.IntegerField()),
                ('place', models.IntegerField()),
                ('taken_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
