# Generated by Django 4.2.10 on 2024-04-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0008_remove_citizenshipmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='citizenship',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sdu_dorm.citizenshipmodel'),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='address_certificate',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='application',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='form_075',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='identity_card',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='payment_check',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='power_of_attorney',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='university_admission_form',
            field=models.FileField(upload_to=''),
        ),
    ]
