# Generated by Django 4.2.10 on 2024-04-23 15:47

from django.db import migrations, models
import sdu_dorm.models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0010_rename_takenplace_takenplaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='address_certificate',
            field=models.FileField(blank=True, upload_to=sdu_dorm.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='application',
            field=models.FileField(blank=True, upload_to=sdu_dorm.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='form_075',
            field=models.FileField(blank=True, upload_to=sdu_dorm.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='identity_card',
            field=models.FileField(blank=True, upload_to=sdu_dorm.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='payment_check',
            field=models.FileField(blank=True, upload_to=sdu_dorm.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='photo',
            field=models.FileField(blank=True, upload_to=sdu_dorm.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='power_of_attorney',
            field=models.FileField(blank=True, upload_to=sdu_dorm.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='uploaddocumentsmodel',
            name='university_admission_form',
            field=models.FileField(blank=True, upload_to=sdu_dorm.models.get_upload_path),
        ),
    ]
