# Generated by Django 4.2.10 on 2024-02-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reservation',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
