# Generated by Django 4.2.10 on 2024-04-29 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0012_remove_paymentmodel_id_paymentmodel_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
