# Generated by Django 4.2.10 on 2024-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0012_alter_aboutpiece_id_alter_aboutpiece_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.TextField(default='Mail title')),
                ('main_description', models.TextField(default='some text for test')),
                ('mission_title', models.TextField(default='Mission title')),
                ('mission_description', models.TextField(default='Mission description')),
                ('responsibilities_title', models.TextField(default='Responsibilities title')),
                ('responsibilities_description', models.TextField(default='Responsibilities description')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='media/profile_pics/default.jpg', upload_to='media/profile_pics'),
        ),
    ]
