# Generated by Django 4.2.10 on 2024-03-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0013_mainpagemodel_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagemodel',
            name='image1',
            field=models.ImageField(blank=True, upload_to='main_page'),
        ),
        migrations.AlterField(
            model_name='aboutpiece',
            name='image',
            field=models.FileField(upload_to='about'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
