# Generated by Django 4.2.10 on 2024-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0014_mainpagemodel_image1_alter_aboutpiece_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagemodel',
            name='image2',
            field=models.ImageField(blank=True, upload_to='main_page'),
        ),
        migrations.AddField(
            model_name='mainpagemodel',
            name='image3',
            field=models.ImageField(blank=True, upload_to='main_page'),
        ),
        migrations.AddField(
            model_name='mainpagemodel',
            name='image4',
            field=models.ImageField(blank=True, upload_to='main_page'),
        ),
        migrations.AddField(
            model_name='mainpagemodel',
            name='image5',
            field=models.ImageField(blank=True, upload_to='main_page'),
        ),
    ]
