# Generated by Django 4.2.10 on 2024-05-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdu_dorm', '0017_alter_customuser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='status',
            new_name='booking_status',
        ),
    ]
